server:
  port: 8082
  servlet:
    context-path: /v1/ms-services/application-roles/

spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  jackson:
    default-property-inclusion: non-null
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC

