# Security Constraints
security:
  oauth2:
    resource:
        tokenInfoUri: ${OAUTH_TOKEN_URI:http://localhost:8080/oauth/check_token/}
        token-type: Bearer
    client:
      client-id: ${OAUTH_CLIENT_ID:example}
      client-secret: ${OAUTH_CLIENT_SECRET:my-pwd-test}

# Database Configurations
spring:
    datasource:
        platform: postgres
        url: ${DS_DB_URL:jdbc:postgresql://localhost:5432/example}
        username: ${DS_USERNAME:example-usr}
        password: ${DS_PWD:example-pwd}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl                
        show-sql: true
        generate-ddl: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                default_schema: ${DS_SCHEMA:test_schema}

com:
    vcgdev:
        crypto:
            pwd: test-pwd
            saltString: salt-test
            ivSpec: ZNJpc2QM76o+DrCWowWPtw==