server:
  port: 8080
  servlet:
    context-path: /v1/ms-services/application-roles/

spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  jackson:
    default-property-inclusion: non-empty
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
  application:
    name: app-roles

